export const steps = document.querySelectorAll(".step");
export const form = document.querySelector("form");
export const allSection = document.querySelectorAll(".section");
export const personalInfo_Inputs = form?.querySelectorAll(".personal_info input");
export const email = document.getElementById("email");
export const phoneNumber = document.getElementById("phone");
export const inputsErrMsgEL = form?.querySelectorAll(".error-msg");
export const plans = form?.querySelectorAll(".plan");
export const plansSubscription = document.querySelectorAll(".subscription_price");
export const planPromos = document.querySelectorAll(".promo");
export const toggleBtn = document.getElementById("toggle");
export const addOns = form?.querySelectorAll(".add-on_feature");
export const summarySection = document.querySelector(".finishing_up");
export const addOnPrice = document.querySelectorAll(".add-on_price");
export const changePlanType = form?.querySelector(".change_plan");
export const selectedAddOnsContainer = document.querySelector(".add-ons_section");
export const summaryTotals = document.querySelector(".summary_total");
export const totalPrice = document.querySelector(".total_price");
export const btnContainer = document.querySelector(".btn_container");
////////////////////////////////
//# sourceMappingURL=select.js.map